Task 1

In [ ]:
class KK_tea:
  sales = {'KK Regular Tea': 0}
  def __init__(self, price, bag = 50, name = 'Regular'):
    self.name = f'KK {name} Tea'
    self.price = price
    self.bags = bag # Number of tea bags
    self.weight = bag*2 # weight of tea bags. per bag --> 2 grams
    self.status = False
  def product_detail(self):
    print(f'Name: {self.name}, Weight: {self.weight}')
    print(f'Tea Bags: {self.bags}, Price: {self.price}')
    print(f'Status: {self.status}')

  @classmethod
  def total_sales(cls):
    print(f'Total sales: {cls.sales}')
  @classmethod
  def update_sold_status_regular(cls, *teas):
    for obj in teas:
      if obj.name in cls.sales:
        cls.sales[obj.name] += 1
      else:
        cls.sales[obj.name] = 1
      obj.status = True

class KK_flavoured_tea(KK_tea):
  def __init__(self, name, price, bag):
    #KK_tea.__init__(self, price, bag) # or,
    super().__init__(price, bag, name)

  @classmethod
  def update_sold_status_flavoured(cls, *teas):
    KK_tea.update_sold_status_regular(*teas)

t1 = KK_tea(250)
print("-----------------1-----------------")
t1.product_detail()
print("-----------------2-----------------")
KK_tea.total_sales()
print("-----------------3-----------------")
t2 = KK_tea(470, 100)
t3 = KK_tea(360, 75)
KK_tea.update_sold_status_regular(t1, t2, t3)
print("-----------------4-----------------")
t3.product_detail()
print("-----------------5-----------------")
KK_tea.total_sales()
print("-----------------6-----------------")
t4 = KK_flavoured_tea("Jasmine", 260, 50)
t5 = KK_flavoured_tea("Honey Lemon", 270, 45)
t6 = KK_flavoured_tea("Honey Lemon", 270, 45)
print("-----------------7-----------------")
t4.product_detail()
print("-----------------8-----------------")
t6.product_detail()
print("-----------------9-----------------")
KK_flavoured_tea.update_sold_status_flavoured(t4, t5, t6)
print("-----------------10-----------------")
KK_tea.total_sales()

-----------------1-----------------
Name: KK Regular Tea, Weight: 100
Tea Bags: 50, Price: 250
Status: False
-----------------2-----------------
Total sales: {'KK Regular Tea': 0}
-----------------3-----------------
-----------------4-----------------
Name: KK Regular Tea, Weight: 150
Tea Bags: 75, Price: 360
Status: True
-----------------5-----------------
Total sales: {'KK Regular Tea': 3}
-----------------6-----------------
-----------------7-----------------
Name: KK Jasmine Tea, Weight: 100
Tea Bags: 50, Price: 260
Status: False
-----------------8-----------------
Name: KK Honey Lemon Tea, Weight: 90
Tea Bags: 45, Price: 270
Status: False
-----------------9-----------------
-----------------10-----------------
Total sales: {'KK Regular Tea': 3, 'KK Jasmine Tea': 1, 'KK Honey Lemon Tea': 2}

Task 2

In [ ]:
class Tournament:
  def __init__(self,name='Default'):
    self.__name = name
  def set_name(self,name):
    self.__name = name
  def get_name(self):
    return self.__name


class Cricket_Tournament(Tournament):
  def __init__(self, name='Default', teams = 0, Type = 'No type'):
    super().__init__(name)
    self.teams = teams
    self.Type = Type

  def detail(self):
    a = f'Cricket Tournament Name: {self.get_name()}\n'
    b = f'Number of Teams: {self.teams}\n'
    c = f'Type: {self.Type}'
    return a + b + c

class Tennis_Tournament(Tournament):
  def __init__(self, name, players):
    super().set_name(name)
    self.players = players

  def detail(self):
    a = f'Tennis Tournament Name: {self.get_name()}\n'
    b = f'Number of Players: {self.players}'
    return a + b

ct1 = Cricket_Tournament()
print(ct1.detail())
print("-----------------------")
ct2 = Cricket_Tournament("IPL",10,"t20")
print(ct2.detail())
print("-----------------------")
tt = Tennis_Tournament("Roland Garros",128)
print(tt.detail())

Cricket Tournament Name: Default
Number of Teams: 0
Type: No type
-----------------------
Cricket Tournament Name: IPL
Number of Teams: 10
Type: t20
-----------------------
Tennis Tournament Name: Roland Garros
Number of Players: 128

Task 3

In [ ]:
class Shape:
  def __init__(self, name='Default', height=0, base=0):
    self.area = 0
    self.name = name
    self.height = height
    self.base = base

  def get_height_base(self):
    return "Height: "+str(self.height)+", Base: "+str(self.base)

class triangle(Shape):
  def __init__(self, name = 'Default', height = 0, base = 0):
    super().__init__(name, height, base)
  def calcArea(self):
    self.area = 0.5 * self.height * self.base
  def printDetail(self):
    return f'Shape name: {self.name}\
            \n{self.get_height_base()}\
            \nArea: {self.area}'

class trapezoid(Shape):
  def __init__(self, name = 'Default', height = 0, base = 0, side = 0):
    super().__init__(name, height, base)
    self.side_a = side
  def calcArea(self):
    self.area = (self.side_a + self.base)/2 * self.height
  def printDetail(self):
    return f'Shape name: {self.name}\
            \n{self.get_height_base()}, Side_A: {self.side_a}\
            \nArea: {self.area}'

tri_default = triangle()
tri_default.calcArea()
print(tri_default.printDetail())
print('--------------------------')
tri = triangle('Triangle', 10, 5)
tri.calcArea()
print(tri.printDetail())
print('---------------------------')
trap = trapezoid('Trapezoid', 10, 6, 4)
trap.calcArea()
print(trap.printDetail())

Shape name: Default
Height: 0, Base: 0
Area: 0.0
--------------------------
Shape name: Triangle
Height: 10, Base: 5
Area: 25.0
---------------------------
Shape name: Trapezoid
Height: 10, Base: 6, Side_A: 4
Area: 50.0

Task 4

In [ ]:
class Fruit:
    def __init__(self, formalin=False, name=''):
        self.__formalin = formalin
        self.name = name

    def getName(self):
        return self.name

    def hasFormalin(self):
        return self.__formalin

class testFruit:
    def test(self, f):
        print('----Printing Detail----')
        if f.hasFormalin():
            print('Do not eat the',f.getName(),'.')
            print(f)
        else:
            print('Eat the',f.getName(),'.')
            print(f)

class Mango(Fruit):
  def __init__(self, formalin = True, name = 'Mango'):
    super().__init__(formalin, name)

  def __str__(self):
    return 'Mangos are bad for you'

class Jackfruit(Fruit):
  def __init__(self):
    super().__init__(formalin = False, name = 'Jackfruit')

  def __str__(self):
    return 'Jackfruits are good for you'

m = Mango()
j = Jackfruit()
t1 = testFruit()
t1.test(m)
t1.test(j)

----Printing Detail----
Do not eat the Mango .
Mangos are bad for you
----Printing Detail----
Eat the Jackfruit .
Jackfruits are good for you

Task 5

In [ ]:
class Employee:
  def __init__(self, name, id, dept):
    self.name = name
    self.id = id
    self.dept = dept
    if type(self) is Part_time_employee:
      self.salary = 15000
    else:
      self.salary = 30000

  def employeeDetails(self):
    print(f'Name: {self.name}, Dept {self.dept}\
          \nEmployee id: {self.id}, Salary: {self.salary}')
    if type(self) is Foreign_employee:
      print('Employee Type: Foreign')
    elif type(self) is Part_time_employee:
      print('Employee Type: Part Time')

  def workDistribution(self, dept):
    if dept == 'Human Resource':
      print('Collect work distribution details from the manager.')
    else:
      print('Collect work distribution loads from the HR department.')

  def increment(self):
    if type(self) is Employee:
      self.salary += 0.1*self.salary
    elif type(self) is Foreign_employee:
      self.salary += 0.15*self.salary
    else:
      print('Sadly, there is no increment for the part time employees!!')

class Foreign_employee(Employee):
  def __init__(self, name, id, dept):
    super().__init__(name, id, dept)

class Part_time_employee(Employee):
  def __init__(self, name, id, dept):
    super().__init__(name, id, dept)

print("1------------------------------------------")
emp1=Employee("Nawaz Ali", 102, "Marketing")
print("2------------------------------------------")
emp1.employeeDetails()
print("3------------------------------------------")
emp1.workDistribution("Marketing")
print("4------------------------------------------")
emp1.increment()
emp1.employeeDetails()
print("5------------------------------------------")
f_emp=Foreign_employee("Nadvi", 311, "Human Resource")
f_emp.employeeDetails()
print("6------------------------------------------")
f_emp.workDistribution("Human Resource")
print("7------------------------------------------")
f_emp.increment()
f_emp.employeeDetails()
print("8------------------------------------------")
p1_emp=Part_time_employee("Asif", 210, "Sales")
p2_emp=Part_time_employee("Olive", 223, "Accounts")
print("9------------------------------------------")
p1_emp.employeeDetails()
print("10------------------------------------------")
p1_emp.workDistribution("Sales")
print("11------------------------------------------")
p2_emp.increment()
print("12------------------------------------------")
p2_emp.employeeDetails()

1------------------------------------------
2------------------------------------------
Name: Nawaz Ali, Dept Marketing
Employee id: 102, Salary: 30000
3------------------------------------------
Collect work distribution loads from the HR department.
4------------------------------------------
Name: Nawaz Ali, Dept Marketing
Employee id: 102, Salary: 33000.0
5------------------------------------------
Name: Nadvi, Dept Human Resource
Employee id: 311, Salary: 30000
Employee Type: Foreign
6------------------------------------------
Collect work distribution details from the manager.
7------------------------------------------
Name: Nadvi, Dept Human Resource
Employee id: 311, Salary: 34500.0
Employee Type: Foreign
8------------------------------------------
9------------------------------------------
Name: Asif, Dept Sales
Employee id: 210, Salary: 15000
Employee Type: Part Time
10------------------------------------------
Collect work distribution loads from the HR department.
11------------------------------------------
Sadly, there is no increment for the part time employees!!
12------------------------------------------
Name: Olive, Dept Accounts
Employee id: 223, Salary: 15000
Employee Type: Part Time

Task 6

In [1]:
import math
class Point:
  def __init__(self, x=0, y=0):
    self.x = x
    self.y = y
    self.area = 0

  def calculate_area(self):
    return self.area

  def print_details(self):
    print("--------- Printing details ----------")
    print(f'Co-ordinate: ({self.x},{self.y})')
    print(f'Area: {self.area}')

class Circle(Point):
  def __init__(self, r = 0, x = 0, y = 0):
    super().__init__(x, y)
    self.r = r # r = radius
    self.area = math.pi * r**2
    self.area = round(self.area, 4)

  def print_details(self):
    super().print_details()
    print('Radius:', self.r)

class Sphere(Circle):
  def __init__(self, r = 0, x = 0, y = 0):
    super().__init__(r, x, y)
    # I could also do: Point.__init__(self, x, y)
    #self.r = r
    self.area = 4 * math.pi * r**2
    self.area = round(self.area, 4)


print("--------------1---------------")
p1 = Point(2,3)
print(f'Area of p1: {p1.calculate_area()}')
print("--------------2---------------")
p1.print_details()
print("--------------3---------------")
p2 = Point()
p2.print_details()
print("--------------4---------------")
c1 = Circle(4,0,3)
print(f'Area of c1: {c1.calculate_area()}')
print("--------------5---------------")
c1.print_details()
print("--------------6---------------")
c2 = Circle(7)
print(f'Area of c2: {c2.calculate_area()}')
print("--------------7---------------")
sph1 = Sphere(3,0,2)
print(f'Area of sph1: {sph1.calculate_area()}')
print("--------------8---------------")
sph1.print_details()
print("--------------9---------------")
sph2 = Sphere(6)
print(f'Area of sph2: {sph2.calculate_area()}')

--------------1---------------
Area of p1: 0
--------------2---------------
--------- Printing details ----------
Co-ordinate: (2,3)
Area: 0
--------------3---------------
--------- Printing details ----------
Co-ordinate: (0,0)
Area: 0
--------------4---------------
Area of c1: 50.2655
--------------5---------------
--------- Printing details ----------
Co-ordinate: (0,3)
Area: 50.2655
Radius: 4
--------------6---------------
Area of c2: 153.938
--------------7---------------
Area of sph1: 113.0973
--------------8---------------
--------- Printing details ----------
Co-ordinate: (0,2)
Area: 113.0973
Radius: 3
--------------9---------------
Area of sph2: 452.3893

Task 7

In [ ]:
class Account:
    def __init__(self, account_number, balance):
      self.account_number = account_number
      self.balance = balance
      self.account_type = "General"
      self.maturity = 0


    def print_details(self):
      print("------ Account details ------")
      print(f"Account Type: {self.account_type}, Maturity: {self.maturity} years")
      print(f"Account Number: {self.account_number}, Balance: ${self.balance:.2f}")


    def deposit(self, amount):
      self.balance += amount
      print(f"Deposited ${amount:.2f}. New Balance: ${self.balance:.2f}")


    def withdraw(self, amount):
      if self.balance >= amount:
          self.balance -= amount
          print(f"Withdrew ${amount:.2f}. New Balance: ${self.balance:.2f}")
      else:
          print("Insufficient funds.")


    def year_passed(self, year):
      self.maturity += year
      print(f"Maturity of the account: {self.maturity} years")

class SavingsAccount(Account):
  def __init__(self, account_type, account_number, balance, rate, limit):
    super().__init__(account_number, balance)
    self.account_type = account_type
    self.interest_rate = rate
    self.min_limit = limit

  def print_details(self):
    super().print_details()
    print(f'Interest Rate: {self.interest_rate}, Minimum Limit: ${self.min_limit}')

  def withdraw(self, amount):
    if (self.balance - amount) >= self.min_limit:
      super().withdraw(amount)
    else:
      print("Insufficient funds.")

  def apply_interest(self):
    self.balance += self.balance * self.interest_rate
    print(f'Interest applied. New Balance: ${self.balance}')

class FixedDepositAccount(Account):
  def __init__(self, account_type, account_number, balance, limit):
    super().__init__(account_number, balance)
    self.account_type = account_type
    self.maturity_limit = limit

  def deposit(self, amount):
    print('You can not deposit in a fixed deposit account.')

  def withdraw(self, amount):
    if self.maturity >= self.maturity_limit:
      super().withdraw(amount)
    else:
      print('Can not withdraw, Account is not matured')


print("-----------1------------")
account = Account("A203", 2000)
account.print_details()
print("-----------2------------")
account.deposit(400)
account.withdraw(1500)
account.year_passed(2)
print("-----------3------------")
account.print_details()
print("-----------4------------")
savings_account = SavingsAccount("Savings","SA123", 1000, 0.05, 500)
savings_account.print_details()
print("-----------5------------")
savings_account.deposit(400)
print("-----------6------------")
savings_account.withdraw(1000)
print("-----------7------------")
savings_account.withdraw(800)
print("-----------8------------")
savings_account.apply_interest()
print("-----------9------------")
savings_account.print_details()
print("-----------10------------")
fixed_account1= FixedDepositAccount("Fixed Deposit","FDA321", 10000, 5)
fixed_account1.print_details()
print("-----------11------------")
fixed_account1.deposit(400)
print("-----------12------------")
fixed_account1.year_passed(6)
print("-----------13------------")
fixed_account1.withdraw(10000)
print("-----------14------------")
fixed_account1.print_details()
print("-----------15------------")
fixed_account2 = FixedDepositAccount("Fixed Deposit","FDA300", 50000, 7)
fixed_account2.print_details()
print("-----------16------------")
fixed_account2.withdraw(10000)

-----------1------------
------ Account details ------
Account Type: General, Maturity: 0 years
Account Number: A203, Balance: $2000.00
-----------2------------
Deposited $400.00. New Balance: $2400.00
Withdrew $1500.00. New Balance: $900.00
Maturity of the account: 2 years
-----------3------------
------ Account details ------
Account Type: General, Maturity: 2 years
Account Number: A203, Balance: $900.00
-----------4------------
------ Account details ------
Account Type: Savings, Maturity: 0 years
Account Number: SA123, Balance: $1000.00
Interest Rate: 0.05, Minimum Limit: $500
-----------5------------
Deposited $400.00. New Balance: $1400.00
-----------6------------
Insufficient funds.
-----------7------------
Withdrew $800.00. New Balance: $600.00
-----------8------------
Interest applied. New Balance: $630.0
-----------9------------
------ Account details ------
Account Type: Savings, Maturity: 0 years
Account Number: SA123, Balance: $630.00
Interest Rate: 0.05, Minimum Limit: $500
-----------10------------
------ Account details ------
Account Type: Fixed Deposit, Maturity: 0 years
Account Number: FDA321, Balance: $10000.00
-----------11------------
You can not deposit in a fixed deposit account.
-----------12------------
Maturity of the account: 6 years
-----------13------------
Withdrew $10000.00. New Balance: $0.00
-----------14------------
------ Account details ------
Account Type: Fixed Deposit, Maturity: 6 years
Account Number: FDA321, Balance: $0.00
-----------15------------
------ Account details ------
Account Type: Fixed Deposit, Maturity: 0 years
Account Number: FDA300, Balance: $50000.00
-----------16------------
Can not withdraw, Account is not matured